### ISSUE TITLE
常にライトモードにしたい

### ISSUE THREAD

**Issue by takazoe** [k-miyata/notemu-chromeextension#13]
OSの外観モードがダークモードの場合もnoteは常にライトモード（背景がライトグレー）になるよう設定することは可能でしょうか？

**Comment by k-miyata** [comment]
今のところそのような機能はありませんが、そのように設定できるよう機能を追加することは可能だと思います。

差し支えなければ、OSの外観モードがダークモードでもnoteでは常にライトモード（背景がライトグレー）にしたい理由をご教示いただけますでしょうか。

**Comment by takazoe** [comment]
ご返信ありがとうございます🙇

個人的な理由なのですが、私はOSはダークモードに設定し、文章を読むアプリ(NotionやWordなど)だけはライトモードに設定するのが好みです
そのため、note-friendlyにそのような機能があるか知りたく質問いたしました

**Comment by k-miyata** [comment]
ありがとうございます。他にも同様の好みを持つ方がいらっしゃるような気がするので、機能追加を行おうと思います。

note friendlyに設定画面を追加し、そこでnoteのモードを

- OSの外観モードに合わせる
- 常にライトモード
- 常にダークモード

から選択できるようにしようと思います。

仕事の合間での開発なので機能をご提供できるまで時間がかかるかもしれませんが、気長にお待ちいただけるとうれしいです。

**Comment by takazoe** [comment]
ありがとうございます!
機能追加、楽しみに待っております

**Comment by k-miyata** [comment]
@takazoe 大変お待たせいたしました。先日、本機能をリリースいたしました。拡張機能note friendlyのアイコンをクリックすると設定画面が表示されますので、そこで「ライト」を選択していただくことにより、noteを常にライトモードにすることができます。

もし色が変わらない場合は、一度noteのページを再読み込みしてみてください。

<img width="206" alt="スクリーンショット 2024-07-06 22 06 33" src="https://github.com/k-miyata/note-friendly/assets/18201546/dde7d4e2-530d-4566-9d44-b6eec19b2e05">

**Comment by takazoe** [comment]
@k-miyata
ありがとうございます！
さっそく使わせていただきます
